# Generated by Django 4.1 on 2022-09-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_lose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lose',
        ),
    ]
