# Generated by Django 4.1 on 2022-09-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_leaderboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'verbose_name': 'User', 'verbose_name_plural': 'LeaderBoard'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['rank'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='answer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logic.questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logic.quiz'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.answer'),
        ),
    ]
