# Generated by Django 4.1 on 2022-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_groups_player_final_score_player_login_player_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='login',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passed_tests',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
