# Generated by Django 4.1 on 2022-09-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_alter_leaderboard_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logic.quiz'),
        ),
    ]
