# Generated by Django 4.1 on 2022-09-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_remove_player_login_remove_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='passed_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
