# Generated by Django 4.1 on 2022-09-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_alter_answer_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['rank'], 'verbose_name': 'LeaderBoard', 'verbose_name_plural': 'Leaderboard'},
        ),
        migrations.AddField(
            model_name='player',
            name='detail',
            field=models.TextField(default='No info yet'),
        ),
    ]
