# Generated by Django 4.1 on 2022-09-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logic', '0005_player_passed_tests_player_phone_number_player_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
