# Generated by Django 4.1 on 2022-09-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_alter_quiz_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logic.answer'),
        ),
    ]
