# Generated by Django 4.1 on 2022-09-07 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_options'),
        ('logic', '0006_alter_leaderboard_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='option_1',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='score_for_answering',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='timer',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='score_for_answering',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='timer',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logic.answer'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
