# Generated by Django 4.1 on 2022-09-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_alter_quiz_options_remove_quiz_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['pk'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='group',
        ),
    ]
