# Generated by Django 4.1 on 2022-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_alter_player_options_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['pk'], 'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(to='logic.questions'),
        ),
    ]
