# Generated by Django 4.1 on 2022-09-05 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_alter_questions_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Score_for_answering',
            new_name='score_for_answering',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_done_by_players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
