# Generated by Django 4.1 on 2022-09-05 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_rename_score_for_answering_answer_score_for_answering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_done_by_players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
