# Generated by Django 4.1 on 2022-09-05 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0012_questions_is_done_by_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='passed_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='is_done_by_players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
