# Generated by Django 4.1 on 2022-09-05 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_player_passed_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone_number',
            field=models.IntegerField(blank=True, default=555),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_done_by_players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
