# Generated by Django 4.1 on 2022-09-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0014_player_phone_number_alter_quiz_is_done_by_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
