# Generated by Django 4.1 on 2022-09-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logic', '0015_delete_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
