# Generated by Django 4.1 on 2022-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logic', '0016_player_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['rank']},
        ),
        migrations.RemoveField(
            model_name='player',
            name='group',
        ),
        migrations.AlterField(
            model_name='player',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(blank=True, default=999),
        ),
    ]
